### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Sparkinman** [sparky3387/NVIDIAControlDevice#3]
Forgive me, but I now have this up and running, and connected to wifi and the shield via bluetooth.  I haven't been able to get any of the kodi apps mentioned to be able to connect, even with the correct IP and port number.  In addition, I'm wondering if there is a way to send the payload from a web browser, and if so what the string would look like... http://IPaddress:port/
Sorry for being new to this!

**Comment by sparky3387** [comment]
If you open the developer settings of the extension (Are you using Kassi?) for me i can do this by going to chrome-extension://jgannjdjlpnoibphpbmmfjkejcfhcmjp/settings.html and pressing f12 on the keyboard, you can also manually test your connection to the ESP32 using curl, you should get ok responses, i dont have this setup but you should be able to find examples here

https://forum.kodi.tv/showthread.php?tid=327119

**Comment by sparky3387** [comment]
Closing old report
